#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore &

exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

picom &

bash ~/.config/polybar/launch.sh &
(sleep 1 && nm-applet) &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
